version: '3.1'
services:
  open-elevation:
    container_name: docker
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    networks:
      - elevnet
    ports:
      - "10000:10000"
    volumes:
      - ./data:/code/data
networks:
  elevnet:
    driver: bridge
